# Required: local settings
local :
  root_dir : <%= ENV['TRAVIS_BUILD_DIR'] %>

# Required: deployment targets
targets :
  - type : "bintray"
    user : <%= ENV['BINTRAY_SNOWPLOW_GENERIC_USER'] %>
    password : <%= ENV['BINTRAY_SNOWPLOW_GENERIC_API_KEY'] %>

# Required: packages to be deployed
packages :
  - repo : "snowplow-generic"
    name : "snowplow-event-recovery"
    user_org : "snowplow"
    publish : true
    override : false
    continue_on_conflict : false
    version : <%= FUNC['sbt_version(.)'] %>
    build_version : <%= ENV['TRAVIS_BUILD_RELEASE_TAG'] %>
    build_commands :
      - sbt "project beam" universal:packageBin
    artifacts :
      - type : "asis"
        prefix : "snowplow_event_recovery_beam_"
        suffix : ".zip"
        binary_paths :
          - "beam/target/universal/snowplow-event-recovery-beam-{{ packages.0.build_version }}.zip"
